/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/bugatti.glb -t
Author: SINNIK (https://sketchfab.com/sinnik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bugatti-la-voiture-noire-b713f2e7c48842c194084cf42b0b7a5f
Title: Bugatti - La Voiture Noire
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useCustomizationStore } from "../store/customization";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
  };
  materials: {
    Matte__80800000__env_50_spec_trans: THREE.MeshStandardMaterial;
    lavoiturecsr2_badge__env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_grille1__env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_grille2__env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_grille3__env_50_spec: THREE.MeshStandardMaterial;
    vehiclelights128__env_50_spec_FL: THREE.MeshStandardMaterial;
    vehiclelights128__env_50_spec_FR: THREE.MeshStandardMaterial;
    vehiclelights128__env_50_spec_RR: THREE.MeshStandardMaterial;
    Matte__80202020__env_50_spec_trans: THREE.MeshStandardMaterial;
    Matte__FF114182__sec_env_50_spec: THREE.MeshStandardMaterial;
    Matte__FF151515__spec: THREE.MeshStandardMaterial;
    Matte__FFFFFFFF__prim_env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_coloured__env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_light__env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_textured2a__spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_textureda__env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_wheel__env_50_spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_wheel__spec: THREE.MeshStandardMaterial;
    lavoiturecsr2_wheeltextured__env_50_spec: THREE.MeshStandardMaterial;
  };
};

export function Bugatti(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/bugatti.glb") as GLTFResult;
  // const bodyColor = new THREE.MeshStandardMaterial({ color: "red" });
  const {
    bodyColor: bc,
    hubcapColor: hc,
    bodySecondaryColor: sc,
  } = useCustomizationStore();
  const bodyColor = new THREE.MeshStandardMaterial({
    color: `${bc}`,
    roughness: 0.2,
  });
  const hubcapColor = new THREE.MeshStandardMaterial({
    color: `${hc}`,
    roughness: 0.2,
  });
  const bodySecondaryColor = new THREE.MeshStandardMaterial({
    color: `${sc}`,
    roughness: 0.2,
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Matte__80800000__env_50_spec_trans}
        />
        {/* not this one below */}
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.lavoiturecsr2_badge__env_50_spec}
        />
        {/* exhaust color */}
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.lavoiturecsr2_grille1__env_50_spec}
        />
        {/* car bottom */}
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.lavoiturecsr2_grille2__env_50_spec}
        />
        {/* dont even bother */}
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.lavoiturecsr2_grille3__env_50_spec}
        />
        {/* left light */}
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.vehiclelights128__env_50_spec_FL}
        />
        {/* right light */}
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.vehiclelights128__env_50_spec_FR}
        />
        {/* rear light */}
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.vehiclelights128__env_50_spec_RR}
        />
        {/* every thing with glass material */}
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Matte__80202020__env_50_spec_trans}
        />
        {/* car skirt */}
        <mesh
          geometry={nodes.Object_11.geometry}
          material={bc ? bodyColor : materials.Matte__FF114182__sec_env_50_spec}
        />
        {/* inside body obv */}
        <mesh
          geometry={nodes.Object_12.geometry}
          material={sc ? bodySecondaryColor : materials.Matte__FF151515__spec}
        />
        {/* whole body except doors and skirt */}
        <mesh
          geometry={nodes.Object_13.geometry}
          material={
            bc ? bodyColor : materials.Matte__FFFFFFFF__prim_env_50_spec
          }
        />
        {/* vechile doors */}
        <mesh
          geometry={nodes.Object_14.geometry}
          material={
            bc ? bodyColor : materials.Matte__FFFFFFFF__prim_env_50_spec
          }
        />
        {/* add to customization menu. car lines and front */}
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.lavoiturecsr2_coloured__env_50_spec}
        />
        {/* car rear */}
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.lavoiturecsr2_coloured__env_50_spec}
        />
        {/* mirrors */}
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.lavoiturecsr2_coloured__env_50_spec}
        />
        {/* car rear lights and text */}
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.lavoiturecsr2_light__env_50_spec}
        />
        {/* inside colors like chair etc */}
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.lavoiturecsr2_textured2a__spec}
        />
        {/* inside doors */}
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.lavoiturecsr2_textured2a__spec}
        />
        {/* car exhauts */}
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.lavoiturecsr2_textureda__env_50_spec}
        />
        {/* car front seperated */}
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.lavoiturecsr2_textureda__env_50_spec}
        />
        {/* wheeles */}
        <mesh
          geometry={nodes.Object_23.geometry}
          material={
            hc ? hubcapColor : materials.lavoiturecsr2_wheel__env_50_spec
          }
        />
        {/* car tires */}
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.lavoiturecsr2_wheel__spec}
        />
        {/* wheel rear thing */}
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.lavoiturecsr2_wheeltextured__env_50_spec}
        />
        {/* wheel rear thing */}
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.lavoiturecsr2_wheeltextured__env_50_spec}
        />
        {/* wheel rear thing */}
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.lavoiturecsr2_wheeltextured__env_50_spec}
        />
        {/* wheel rear thing */}
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.lavoiturecsr2_wheeltextured__env_50_spec}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/bugatti.glb");
